apiVersion: v1
kind: Service
metadata:
  name: dremio-coordinator-ui
  labels:
    app: dremio-ui
spec:
  ports:
  - port: 9047
    name: web
  selector:
    app: dremio-coordinator
  type: {{ .Values.serviceType | default "NodePort" }}
