apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-master
  labels:
    app: dremio-master
spec:
  serviceName: "dremio-master"
  replicas: {{.Values.coordinator.master_count}}
  selector:
    matchLabels:
      app: dremio-coordinator
  template:
    metadata:
      labels:
        app: dremio-coordinator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - dremio-master
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 5
      containers:
      - name: dremio-master-coordinator
        image: {{.Values.image}}
        resources:
          requests:
            memory: {{.Values.coordinator.memory}}M
            cpu: {{.Values.coordinator.cpu}}
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        env:
        - name: DIST_PATH
          value: {{.Values.path.dist}}
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "{{ template "HeapMemory" .Values.coordinator.memory }}"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "{{ template "DirectMemory" .Values.coordinator.memory }}"
        - name: LOCAL_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["/opt/dremio/bin/dremio"]
        args:
        - "start-fg"
        - ""
        - "-Dzookeeper=zk-hs:2181"
        - "-Dregistration.publish-host=$(LOCAL_POD_IP)"
        - "-Dservices.coordinator.master.embedded-zookeeper.enabled=false"
        - "-Dservices.executor.enabled=false"
        - "-Dpaths.dist=$(DIST_PATH)"
        ports:
        - containerPort: 9047
          name: web
        - containerPort: 31010
          name: client
        - containerPort: 45678
          name: server
      initContainers:
      - name: wait-for-zk
        image: busybox
        command:  ["sh", "-c", "until ping -c 1 -W 1 zk-hs > /dev/null; do echo waiting for zookeeper host; sleep 2; done;"]
      # since we're mounting a separate volume, reset permission to dremio uid/gid (999:999)
      - name: chown-data-directory
        image: busybox
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["chown"]
        args:
        - "999:999"
        - "/opt/dremio/data"
      - name: upgrade-task
        image: {{.Values.image}}
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["/opt/dremio/bin/dremio-admin"]
        args:
        - "upgrade"
      volumes:
      - name: dremio-master-volume
        persistentVolumeClaim:
          claimName: dremio-master-volume
