apiVersion: v1
kind: Service
metadata:
  name: dremio-client
  labels:
    app: dremio-client
spec:
  ports:
  - port: 31010
    name: client
  selector:
    app: dremio-coordinator
  type: {{ .Values.serviceType | default "NodePort" }}
