apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dremio-executor
spec:
  serviceName: "dremio-executor"
  replicas: {{.Values.executor.count}}
  selector:
    matchLabels:
      app: dremio-executor
  template:
    metadata:
      labels:
        app: dremio-executor
    spec:
      containers:
      - name: dremio-executor
        image: {{.Values.image}}
        resources:
          requests:
            memory: {{.Values.executor.memory}}M
            cpu: {{.Values.executor.cpu}}
        env:
        - name: DIST_PATH
          value: {{.Values.path.dist}}
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "{{ template "HeapMemory" .Values.executor.memory }}"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "{{ template "DirectMemory" .Values.executor.memory }}"
        - name: LOCAL_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["/opt/dremio/bin/dremio"]
        args:
        - "start-fg"
        - ""
        - "-Dzookeeper=zk-hs:2181"
        - "-Dregistration.publish-host=$(LOCAL_POD_IP)"
        - "-Dservices.coordinator.enabled=false"
        - "-Dpaths.dist=$(DIST_PATH)"
        ports:
        - containerPort: 45678
          name: server
      initContainers:
      - name: wait-for-zk
        image: busybox
        command:  ["sh", "-c", "until nc -z dremio-coordinator-ui 9047 > /dev/null; do echo waiting for zookeeper host; sleep 2; done;"]
