kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dremio-master-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  selector:
    matchLabels:
      role: dremio-master
