{{ if not .Values.DremioAdmin }}
apiVersion: v1
kind: Service
metadata:
  name: dremio-prometheus
  labels:
    app: dremio-prometheus
spec:
  ports:
    - port: 12543
      name: prometheus
  selector:
    role: dremio-cluster-pod
  type: {{ .Values.serviceType | default "NodePort" }}
  {{- if .Values.sessionAffinity }}
  sessionAffinity: {{ .Values.sessionAffinity }}
  {{- end }}
{{ end }}
