apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dremio-coordinator
spec:
  serviceName: "dremio-coordinator"
  replicas: {{.Values.coordinator.count}}
  selector:
    matchLabels:
      app: dremio-coordinator
  template:
    metadata:
      labels:
        app: dremio-coordinator
    spec:
      containers:
      - name: dremio-coordinator
        image: {{.Values.image}}
        resources:
          requests:
            memory: {{.Values.coordinator.memory}}M
            cpu: {{.Values.coordinator.cpu}}
        env:
        - name: DIST_PATH
          value: {{.Values.path.dist}}
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "{{ template "HeapMemory" .Values.coordinator.memory }}"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "{{ template "DirectMemory" .Values.coordinator.memory }}"
        - name: LOCAL_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["/opt/dremio/bin/dremio"]
        args:
        - "start-fg"
        - ""
        - "-Dzookeeper=zk-hs:2181"
        - "-Dregistration.publish-host=$(LOCAL_POD_IP)"
        - "-Dservices.coordinator.master.enabled=false"
        - "-Dservices.executor.enabled=false"
        - "-Dpaths.dist=$(DIST_PATH)"
        ports:
        - containerPort: 9047
          name: web
        - containerPort: 31010
          name: client
        - containerPort: 45678
          name: server
      initContainers:
      - name: wait-for-zk
        image: busybox
        command:  ["sh", "-c", "until nc -z zk-hs 2181; do echo waiting for zookeeper; sleep 2; done;"]
