apiVersion: v1
kind: Service
metadata:
  name: dremio-client
  labels:
    app: dremio-client
spec:
  ports:
  - port: {{ .Values.coordinator.client.port | default 31010 }}
    targetPort: 31010
    name: client
  - port: {{ .Values.coordinator.web.port | default 9047 }}
    targetPort: 9047
    name: web
  selector:
    app: dremio-coordinator
  type: {{ .Values.serviceType | default "NodePort" }}
  sessionAffinity: ClientIP
