apiVersion: v1
kind: PersistentVolume
metadata:
  name: dremio-master-volume
  labels:
    role: dremio-master
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/dremio/dremio-master-volume"
